Add DMA functionality
AltOS-Rust/cm0-port pull request #16
Opened 2017-05-20 03:34 UTC by RJ-Russell

Implement DMA driver.

Tested by adding a task that uses the DMA to transmit data to the Usart and out to minicom.

@dnseitz

2017-05-27 00:43 UTC, dnseitz requested changes

2017-05-27 00:43 UTC, dnseitz commented on Makefile
> +native-args = --features "test serial"
Any reason this was added?

2017-05-27 00:43 UTC, dnseitz commented on src/exceptions/dma.rs
> +#![cfg(feature="dma")]
This should be moved to the module definition in `src/exceptions/mod.rs` to stay consistent with how it was done for `serial`

2017-05-27 00:43 UTC, dnseitz commented on src/io/mod.rs
> +    struct DMASerial {
Moving all these implementations into it's own module seems like it would make the file a bit cleaner.

2017-05-27 00:43 UTC, dnseitz commented on src/lib.rs
> +unsafe { application_entry() };
Reindent this line

2017-05-27 00:43 UTC, dnseitz commented on src/peripheral/dma/ccr.rs
> +    Reserved,
Any reason to have a reserved variant? Seems like it's just reserved by hardware and you shouldn't be able to set it to that value.

2017-05-27 04:00 UTC, RJ-Russell commented on src/peripheral/dma/ccr.rs
> +    Reserved,
Yes.
```Bits 11:10 MSIZE[1:0]: Memory size
These bits are set and cleared by software.
    00: 8-bits
    01: 16-bits
    10: 32-bits
    11: Reserved 
```
There is an option for the setting so it should be included. As the description states, these bits are `set and cleared by software`.

2017-05-31 21:34 UTC, dnseitz commented on src/peripheral/dma/ccr.rs
> +    Reserved,
But Reserved generally means reserved by hardware, and that it's not a valid configuration. Correct me if it says explicitly that setting the bits to that value actually has some valid behavior.

2017-06-02 04:27 UTC, RJ-Russell commented on src/peripheral/dma/ccr.rs
> +    Reserved,
Yeah. Data sheet is kind of confusing. I removed the Reserved option. Let me know if there is anything else I should look at. Thanks.

2017-06-02 17:18 UTC, dnseitz approved these changes

2017-06-02 17:20 UTC, merged